import { useState } from 'react'
import { LoaderCircle } from 'lucide-react'
import { splitList } from '../lib/format'

export const emptyInternshipForm = {
  title:'',department:'',category:'Web Development',location:'',workMode:'remote',experienceLevel:'beginner',durationMonths:'3',openings:'1',
  compensationType:'paid',stipendMin:'',stipendMax:'',currency:'INR',stipendPeriod:'monthly',startDate:'',deadline:'',
  skillsRequired:'',preferredSkills:'',eligibility:'',description:'',responsibilities:'',perks:'',screeningSteps:'',
}

export function internshipToForm(item={}){return {
  title:item.title||'',department:item.department||'',category:item.category||'Web Development',location:item.location||'',workMode:item.work_mode||'remote',experienceLevel:item.experience_level||'beginner',durationMonths:item.duration_months??'',openings:item.openings??1,
  compensationType:item.compensation_type||'paid',stipendMin:item.stipend_min??'',stipendMax:item.stipend_max??'',currency:item.currency||'INR',stipendPeriod:item.stipend_period||'monthly',startDate:item.start_date||'',deadline:item.deadline||'',
  skillsRequired:splitList(item.skills_required).join(', '),preferredSkills:splitList(item.preferred_skills).join(', '),eligibility:splitList(item.eligibility).join(', '),description:item.description||'',responsibilities:splitList(item.responsibilities).join(', '),perks:splitList(item.perks).join(', '),screeningSteps:splitList(item.screening_steps).join(', '),
}}

export default function InternshipForm({ initialValues=emptyInternshipForm, onSaveDraft, onSubmitReview, busyAction='' }){
  const [form,setForm]=useState(initialValues)
  const change=(e)=>setForm((current)=>({...current,[e.target.name]:e.target.value}))
  const categories=['Web Development','Mobile Development','Software Engineering','Data Science','Machine Learning','UI/UX Design','Digital Marketing','Finance','Human Resources','Content Writing','Business Development','Other']
  const minDate=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10)
  const field=(label,name,props={})=><label><span className="mb-2 block text-sm font-semibold">{label}</span><input name={name} value={form[name]} onChange={change} className="input" {...props}/></label>
  return <form onSubmit={(e)=>e.preventDefault()} className="space-y-6">
    <section className="card"><h2 className="text-xl font-black">Basic information</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2">{field('Internship title *','title',{required:true})}</div>{field('Department','department')}<label><span className="mb-2 block text-sm font-semibold">Category *</span><select name="category" value={form.category} onChange={change} className="input">{categories.map((c)=><option key={c}>{c}</option>)}</select></label>{field('Location *','location',{required:true})}<label><span className="mb-2 block text-sm font-semibold">Work mode</span><select name="workMode" value={form.workMode} onChange={change} className="input"><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="onsite">On-site</option></select></label><label><span className="mb-2 block text-sm font-semibold">Experience level</span><select name="experienceLevel" value={form.experienceLevel} onChange={change} className="input"><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label>{field('Duration in months','durationMonths',{type:'number',min:1,max:36})}{field('Openings','openings',{type:'number',min:1})}</div></section>
    <section className="card"><h2 className="text-xl font-black">Compensation and dates</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-semibold">Compensation type</span><select name="compensationType" value={form.compensationType} onChange={change} className="input"><option value="paid">Paid</option><option value="unpaid">Unpaid</option></select></label><label><span className="mb-2 block text-sm font-semibold">Stipend period</span><select disabled={form.compensationType==='unpaid'} name="stipendPeriod" value={form.stipendPeriod} onChange={change} className="input"><option value="monthly">Monthly</option><option value="weekly">Weekly</option><option value="daily">Daily</option><option value="fixed">Fixed amount</option></select></label>{field('Minimum stipend','stipendMin',{type:'number',min:0,disabled:form.compensationType==='unpaid'})}{field('Maximum stipend','stipendMax',{type:'number',min:0,disabled:form.compensationType==='unpaid'})}<label><span className="mb-2 block text-sm font-semibold">Currency</span><select disabled={form.compensationType==='unpaid'} name="currency" value={form.currency} onChange={change} className="input"><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option></select></label>{field('Start date','startDate',{type:'date',min:minDate})}{field('Application deadline *','deadline',{type:'date',min:minDate,required:true})}</div></section>
    <section className="card"><h2 className="text-xl font-black">Skills and details</h2><p className="mt-1 text-sm text-slate-500">Separate multiple values with commas.</p><div className="mt-5 space-y-4">{field('Required skills','skillsRequired')}{field('Preferred skills','preferredSkills')}{field('Eligibility','eligibility')}<label className="block"><span className="mb-2 block text-sm font-semibold">Description *</span><textarea required rows="6" name="description" value={form.description} onChange={change} className="input resize-y"/></label><label className="block"><span className="mb-2 block text-sm font-semibold">Responsibilities</span><textarea rows="3" name="responsibilities" value={form.responsibilities} onChange={change} className="input resize-y"/></label>{field('Perks','perks')}{field('Screening steps','screeningSteps')}</div></section>
    <div className="flex flex-wrap justify-end gap-3"><button disabled={Boolean(busyAction)} onClick={()=>onSaveDraft(form)} className="btn-secondary">{busyAction==='draft'?<><LoaderCircle size={17} className="animate-spin"/>Saving…</>:'Save draft'}</button><button disabled={Boolean(busyAction)} onClick={()=>onSubmitReview(form)} className="btn-primary">{busyAction==='review'?<><LoaderCircle size={17} className="animate-spin"/>Submitting…</>:'Submit for approval'}</button></div>
  </form>
}
